"""Role-based editorial and trend radar permissions scoped to tenant context."""

from typing import Set

from fastapi import HTTPException, status

from app.core.tenant import TenantContext

# Role permissions mapping
ROLE_PERMISSIONS = {
    "PLATFORM_ADMIN": {
        "VIEW_EDITORIAL",
        "CREATE_ASSIGNMENT",
        "EDIT_ASSIGNMENT",
        "CREATE_STORY",
        "EDIT_STORY",
        "ADD_SOURCE",
        "CREATE_VERSION",
        "REQUEST_APPROVAL",
        "APPROVE_CONTENT",
        "REJECT_CONTENT",
        "MANAGE_CATEGORIES",
        "VIEW_SOURCES",
        "MANAGE_SOURCES",
        "VIEW_TRENDS",
        "MANAGE_OPPORTUNITIES",
        "TRIGGER_RESEARCH",
        "VIEW_RESEARCH",
        "GENERATE_AI_CONTENT",
        "REVIEW_AI_CONTENT",
        "UPLOAD_MEDIA",
        "VIEW_MEDIA",
        "PROCESS_MEDIA",
        "TRANSCRIBE_MEDIA",
        "GENERATE_DERIVATIVES",
        "REVIEW_MEDIA",
        "EDIT_MEDIA_METADATA",
        "VIEW_PUBLISHING",
        "MANAGE_DESTINATIONS",
        "CREATE_PACKAGE",
        "APPROVE_PUBLISHING",
        "TRIGGER_PUBLISH",
        "CANCEL_PUBLISH",
    },
    "TENANT_OWNER": {
        "VIEW_EDITORIAL",
        "CREATE_ASSIGNMENT",
        "EDIT_ASSIGNMENT",
        "CREATE_STORY",
        "EDIT_STORY",
        "ADD_SOURCE",
        "CREATE_VERSION",
        "REQUEST_APPROVAL",
        "APPROVE_CONTENT",
        "REJECT_CONTENT",
        "MANAGE_CATEGORIES",
        "VIEW_SOURCES",
        "MANAGE_SOURCES",
        "VIEW_TRENDS",
        "MANAGE_OPPORTUNITIES",
        "TRIGGER_RESEARCH",
        "VIEW_RESEARCH",
        "GENERATE_AI_CONTENT",
        "REVIEW_AI_CONTENT",
        "UPLOAD_MEDIA",
        "VIEW_MEDIA",
        "PROCESS_MEDIA",
        "TRANSCRIBE_MEDIA",
        "GENERATE_DERIVATIVES",
        "REVIEW_MEDIA",
        "EDIT_MEDIA_METADATA",
        "VIEW_PUBLISHING",
        "MANAGE_DESTINATIONS",
        "CREATE_PACKAGE",
        "APPROVE_PUBLISHING",
        "TRIGGER_PUBLISH",
        "CANCEL_PUBLISH",
    },
    "TENANT_ADMIN": {
        "VIEW_EDITORIAL",
        "CREATE_ASSIGNMENT",
        "EDIT_ASSIGNMENT",
        "CREATE_STORY",
        "EDIT_STORY",
        "ADD_SOURCE",
        "CREATE_VERSION",
        "REQUEST_APPROVAL",
        "APPROVE_CONTENT",
        "REJECT_CONTENT",
        "MANAGE_CATEGORIES",
        "VIEW_SOURCES",
        "MANAGE_SOURCES",
        "VIEW_TRENDS",
        "MANAGE_OPPORTUNITIES",
        "TRIGGER_RESEARCH",
        "VIEW_RESEARCH",
        "GENERATE_AI_CONTENT",
        "REVIEW_AI_CONTENT",
        "UPLOAD_MEDIA",
        "VIEW_MEDIA",
        "PROCESS_MEDIA",
        "TRANSCRIBE_MEDIA",
        "GENERATE_DERIVATIVES",
        "REVIEW_MEDIA",
        "EDIT_MEDIA_METADATA",
        "VIEW_PUBLISHING",
        "MANAGE_DESTINATIONS",
        "CREATE_PACKAGE",
        "APPROVE_PUBLISHING",
        "TRIGGER_PUBLISH",
        "CANCEL_PUBLISH",
    },
    "EDITOR": {
        "VIEW_EDITORIAL",
        "CREATE_ASSIGNMENT",
        "EDIT_ASSIGNMENT",
        "CREATE_STORY",
        "EDIT_STORY",
        "ADD_SOURCE",
        "CREATE_VERSION",
        "REQUEST_APPROVAL",
        "APPROVE_CONTENT",
        "REJECT_CONTENT",
        "MANAGE_CATEGORIES",
        "VIEW_SOURCES",
        "MANAGE_SOURCES",
        "VIEW_TRENDS",
        "MANAGE_OPPORTUNITIES",
        "TRIGGER_RESEARCH",
        "VIEW_RESEARCH",
        "GENERATE_AI_CONTENT",
        "REVIEW_AI_CONTENT",
        "UPLOAD_MEDIA",
        "VIEW_MEDIA",
        "PROCESS_MEDIA",
        "TRANSCRIBE_MEDIA",
        "GENERATE_DERIVATIVES",
        "REVIEW_MEDIA",
        "EDIT_MEDIA_METADATA",
        "VIEW_PUBLISHING",
        "MANAGE_DESTINATIONS",
        "CREATE_PACKAGE",
        "APPROVE_PUBLISHING",
        "TRIGGER_PUBLISH",
        "CANCEL_PUBLISH",
    },
    "CONTENT_MANAGER": {
        "VIEW_EDITORIAL",
        "CREATE_ASSIGNMENT",
        "EDIT_ASSIGNMENT",
        "CREATE_STORY",
        "EDIT_STORY",
        "ADD_SOURCE",
        "CREATE_VERSION",
        "REQUEST_APPROVAL",
        "APPROVE_CONTENT",
        "REJECT_CONTENT",
        "VIEW_SOURCES",
        "VIEW_TRENDS",
        "MANAGE_OPPORTUNITIES",
        "TRIGGER_RESEARCH",
        "VIEW_RESEARCH",
        "GENERATE_AI_CONTENT",
        "REVIEW_AI_CONTENT",
        "UPLOAD_MEDIA",
        "VIEW_MEDIA",
        "PROCESS_MEDIA",
        "TRANSCRIBE_MEDIA",
        "GENERATE_DERIVATIVES",
        "REVIEW_MEDIA",
        "EDIT_MEDIA_METADATA",
        "VIEW_PUBLISHING",
        "CREATE_PACKAGE",
        "APPROVE_PUBLISHING",
        "TRIGGER_PUBLISH",
        "CANCEL_PUBLISH",
    },
    "REPORTER": {
        "VIEW_EDITORIAL",
        "CREATE_STORY",
        "EDIT_STORY",
        "ADD_SOURCE",
        "CREATE_VERSION",
        "REQUEST_APPROVAL",
        "VIEW_SOURCES",
        "VIEW_TRENDS",
        "TRIGGER_RESEARCH",
        "VIEW_RESEARCH",
        "GENERATE_AI_CONTENT",
        "UPLOAD_MEDIA",
        "VIEW_MEDIA",
        "PROCESS_MEDIA",
        "TRANSCRIBE_MEDIA",
        "GENERATE_DERIVATIVES",
        "EDIT_MEDIA_METADATA",
        "VIEW_PUBLISHING",
        "CREATE_PACKAGE",
    },
    "CREATOR": {
        "VIEW_EDITORIAL",
        "CREATE_STORY",
        "EDIT_STORY",
        "ADD_SOURCE",
        "CREATE_VERSION",
        "REQUEST_APPROVAL",
        "VIEW_SOURCES",
        "VIEW_TRENDS",
        "TRIGGER_RESEARCH",
        "VIEW_RESEARCH",
        "GENERATE_AI_CONTENT",
        "UPLOAD_MEDIA",
        "VIEW_MEDIA",
        "PROCESS_MEDIA",
        "TRANSCRIBE_MEDIA",
        "GENERATE_DERIVATIVES",
        "EDIT_MEDIA_METADATA",
        "VIEW_PUBLISHING",
        "CREATE_PACKAGE",
    },
    "ANALYST": {
        "VIEW_EDITORIAL",
        "VIEW_SOURCES",
        "VIEW_TRENDS",
        "VIEW_RESEARCH",
        "VIEW_MEDIA",
        "VIEW_PUBLISHING",
    },
    "VIEWER": {
        "VIEW_EDITORIAL",
        "VIEW_SOURCES",
        "VIEW_TRENDS",
        "VIEW_RESEARCH",
        "VIEW_MEDIA",
        "VIEW_PUBLISHING",
    },
}


def get_permissions_for_role(role: str) -> Set[str]:
    """Get the set of granted permission strings for a given role."""
    return ROLE_PERMISSIONS.get(role.upper(), set())


def check_permission(context: TenantContext, required_permission: str) -> None:
    """Enforce that the caller's authorized role within the tenant possesses the permission."""
    if context.is_platform_admin:
        return

    permissions = get_permissions_for_role(context.role)
    if required_permission not in permissions:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                f"Permission denied: Role '{context.role}' lacks required permission "
                f"'{required_permission}' in tenant {context.tenant_id}"
            ),
        )
